import { SchemaModel, TableModel, ColumnModel, RelationshipModel } from '@/types/erd';

export interface DDLOptions {
  includeDropTable?: boolean;
  includeSchema?: boolean;
  includeComments?: boolean;
  quoteIdentifiers?: boolean;
}

export function generateMSSQLDDL(schemaModel: SchemaModel, options: DDLOptions = {}): string {
  const {
    includeDropTable = false,
    includeSchema = true,
    includeComments = true,
    quoteIdentifiers = true,
  } = options;

  const lines: string[] = [];

  const quote = (str: string) => (quoteIdentifiers ? `[${str}]` : str);

  // Collect and sort tables deterministically by schema and physical name
  const tables = Object.values(schemaModel.tablesById).sort((a, b) =>
    `${a.schemaName}.${a.physicalName}`.localeCompare(`${b.schemaName}.${b.physicalName}`)
  );

  // Collect schemas
  const schemas = Array.from(new Set(tables.map((t) => t.schemaName || 'dbo'))).sort();

  lines.push('-- =============================================');
  lines.push('-- Generated by ERD Cloud Collaboration Engine');
  lines.push('-- Target DB: MS SQL Server (Deterministic Export)');
  lines.push('-- =============================================\n');

  // 1. Schemas
  if (includeSchema) {
    schemas.forEach((schema) => {
      if (schema !== 'dbo') {
        lines.push(`IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = N'${schema}')`);
        lines.push(`    EXEC('CREATE SCHEMA ${quote(schema)}');`);
        lines.push('GO\n');
      }
    });
  }

  // 2. Drop Foreign Key constraints if drop table is requested
  if (includeDropTable) {
    const relationships = Object.values(schemaModel.relationshipsById);
    relationships.forEach((rel) => {
      const child = schemaModel.tablesById[rel.childTableId];
      if (child && rel.constraintName) {
        lines.push(
          `IF OBJECT_ID(N'${quote(child.schemaName)}.${quote(rel.constraintName)}', N'F') IS NOT NULL`
        );
        lines.push(
          `    ALTER TABLE ${quote(child.schemaName)}.${quote(child.physicalName)} DROP CONSTRAINT ${quote(rel.constraintName)};`
        );
      }
    });
    if (relationships.length > 0) lines.push('GO\n');
  }

  // 3. Create Tables
  tables.forEach((table) => {
    const schema = table.schemaName || 'dbo';
    const tableName = table.physicalName;

    if (includeComments && (table.logicalName || table.comment)) {
      lines.push(`-- Table: ${table.logicalName} (${table.comment || ''})`);
    }

    if (includeDropTable) {
      lines.push(`IF OBJECT_ID(N'${quote(schema)}.${quote(tableName)}', N'U') IS NOT NULL`);
      lines.push(`    DROP TABLE ${quote(schema)}.${quote(tableName)};`);
    }

    lines.push(`CREATE TABLE ${quote(schema)}.${quote(tableName)} (`);

    const columnDefs: string[] = [];

    // Columns sorted by columnOrder
    const cols = table.columnOrder
      .map((id) => table.columnsById[id])
      .filter((col): col is ColumnModel => col !== undefined);

    cols.forEach((col) => {
      let typeStr = col.type.name.toUpperCase();
      if (['VARCHAR', 'NVARCHAR', 'CHAR', 'NCHAR', 'BINARY', 'VARBINARY'].includes(typeStr)) {
        typeStr += `(${col.type.length || 100})`;
      } else if (['DECIMAL', 'NUMERIC'].includes(typeStr)) {
        const p = col.type.precision || 18;
        const s = col.type.scale || 0;
        typeStr += `(${p}, ${s})`;
      }

      let colLine = `    ${quote(col.physicalName)} ${typeStr}`;

      if (col.identity) {
        colLine += ` IDENTITY(${col.identity.seed},${col.identity.increment})`;
      }

      if (col.nullable) {
        colLine += ' NULL';
      } else {
        colLine += ' NOT NULL';
      }

      if (col.defaultExpression) {
        colLine += ` DEFAULT ${col.defaultExpression}`;
      }

      columnDefs.push(colLine);
    });

    // Primary Key Constraint inside CREATE TABLE
    const pkCols = cols.filter((c) => c.isPk);
    if (pkCols.length > 0) {
      const pkColNames = pkCols.map((c) => quote(c.physicalName)).join(', ');
      columnDefs.push(`    CONSTRAINT ${quote(`PK_${tableName}`)} PRIMARY KEY (${pkColNames})`);
    }

    lines.push(columnDefs.join(',\n'));
    lines.push(');');
    lines.push('GO\n');
  });

  // 4. Foreign Keys (ALTER TABLE)
  const sortedRels = Object.values(schemaModel.relationshipsById).sort((a, b) =>
    (a.constraintName || '').localeCompare(b.constraintName || '')
  );

  sortedRels.forEach((rel) => {
    const parent = schemaModel.tablesById[rel.parentTableId];
    const child = schemaModel.tablesById[rel.childTableId];
    if (!parent || !child) return;

    const parentCols = rel.columnMappings
      .map((m) => parent.columnsById[m.parentColumnId]?.physicalName)
      .filter(Boolean)
      .map((name) => quote(name!));

    const childCols = rel.columnMappings
      .map((m) => child.columnsById[m.childColumnId]?.physicalName)
      .filter(Boolean)
      .map((name) => quote(name!));

    if (parentCols.length === 0 || childCols.length === 0) return;

    const constraintName = rel.constraintName || `FK_${child.physicalName}_${parent.physicalName}`;

    lines.push(
      `ALTER TABLE ${quote(child.schemaName || 'dbo')}.${quote(child.physicalName)}`
    );
    lines.push(
      `    ADD CONSTRAINT ${quote(constraintName)} FOREIGN KEY (${childCols.join(', ')})`
    );
    lines.push(
      `    REFERENCES ${quote(parent.schemaName || 'dbo')}.${quote(parent.physicalName)} (${parentCols.join(', ')})`
    );

    if (rel.onDelete && rel.onDelete !== 'NO ACTION') {
      lines.push(`    ON DELETE ${rel.onDelete}`);
    }
    if (rel.onUpdate && rel.onUpdate !== 'NO ACTION') {
      lines.push(`    ON UPDATE ${rel.onUpdate}`);
    }

    lines.push(';');
    lines.push('GO\n');
  });

  return lines.join('\n');
}
