import { SchemaModel, TableModel } from '@/types/erd';

export function generateMySQLDDL(schema: SchemaModel): string {
  const { tablesById, relationshipsById } = schema;
  const lines: string[] = [];

  lines.push('-- ============================================================');
  lines.push('-- MySQL ERD DDL Script Generated by ERD Studio');
  lines.push(`-- Generated Date: ${new Date().toISOString()}`);
  lines.push('-- ============================================================');
  lines.push('');

  // 1. Create Tables
  Object.values(tablesById).forEach((table) => {
    lines.push(`-- Table: ${table.physicalName} (${table.logicalName || ''})`);
    lines.push(`CREATE TABLE \`${table.physicalName}\` (`);

    const colDefs: string[] = [];
    const pkCols: string[] = [];

    table.columnOrder.forEach((colId) => {
      const col = table.columnsById[colId];
      if (!col) return;

      let typeStr = col.type.name.toUpperCase();
      if (col.type.length) {
        typeStr += `(${col.type.length})`;
      }

      if (typeStr === 'UUID') typeStr = 'VARCHAR(36)';
      if (typeStr === 'BOOLEAN') typeStr = 'TINYINT(1)';
      if (typeStr === 'TIMESTAMP') typeStr = 'DATETIME';

      let def = `  \`${col.physicalName}\` ${typeStr}`;

      if (!col.nullable) {
        def += ' NOT NULL';
      } else {
        def += ' NULL';
      }

      if (col.autoIncrement) {
        def += ' AUTO_INCREMENT';
      }

      if (col.logicalName || col.comment) {
        const comment = (col.logicalName || col.comment || '').replace(/'/g, "''");
        def += ` COMMENT '${comment}'`;
      }

      colDefs.push(def);

      if (col.isPk) {
        pkCols.push(`\`${col.physicalName}\``);
      }
    });

    if (pkCols.length > 0) {
      colDefs.push(`  PRIMARY KEY (${pkCols.join(', ')})`);
    }

    lines.push(colDefs.join(',\n'));
    lines.push(`) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='${(table.logicalName || '').replace(/'/g, "''")}';`);
    lines.push('');
  });

  // 2. Add Foreign Key Constraints
  Object.values(relationshipsById).forEach((rel) => {
    const parentTable = tablesById[rel.parentTableId];
    const childTable = tablesById[rel.childTableId];
    if (!parentTable || !childTable) return;

    const parentCols = rel.columnMappings
      .map((m) => parentTable.columnsById[m.parentColumnId]?.physicalName)
      .filter(Boolean)
      .map((name) => `\`${name}\``);

    const childCols = rel.columnMappings
      .map((m) => childTable.columnsById[m.childColumnId]?.physicalName)
      .filter(Boolean)
      .map((name) => `\`${name}\``);

    if (parentCols.length > 0 && childCols.length > 0) {
      const fkName = rel.constraintName || `FK_${childTable.physicalName}_${parentTable.physicalName}`;
      lines.push(`-- FK Constraint: ${fkName}`);
      lines.push(`ALTER TABLE \`${childTable.physicalName}\``);
      lines.push(`  ADD CONSTRAINT \`${fkName}\``);
      lines.push(`  FOREIGN KEY (${childCols.join(', ')})`);
      lines.push(`  REFERENCES \`${parentTable.physicalName}\` (${parentCols.join(', ')})`);
      lines.push(`  ON DELETE ${rel.onDelete}`);
      lines.push(`  ON UPDATE ${rel.onUpdate};`);
      lines.push('');
    }
  });

  return lines.join('\n');
}
