import { SchemaModel, TableModel, ColumnModel } from '@/types/erd';
import { DDLOptions } from './mssql';

export function generatePostgreSQLDDL(schemaModel: SchemaModel, options: DDLOptions = {}): string {
  const {
    includeDropTable = false,
    includeSchema = true,
    includeComments = true,
    quoteIdentifiers = true,
  } = options;

  const lines: string[] = [];

  const quote = (str: string) => (quoteIdentifiers ? `"${str}"` : str);

  // Collect and sort tables deterministically by schema and physical name
  const tables = Object.values(schemaModel.tablesById).sort((a, b) =>
    `${a.schemaName}.${a.physicalName}`.localeCompare(`${b.schemaName}.${b.physicalName}`)
  );

  // Collect schemas
  const schemas = Array.from(new Set(tables.map((t) => t.schemaName || 'public'))).sort();

  lines.push('-- =============================================');
  lines.push('-- Generated by ERD Cloud Collaboration Engine');
  lines.push('-- Target DB: PostgreSQL (Deterministic Export)');
  lines.push('-- =============================================\n');

  // 1. Schemas
  if (includeSchema) {
    schemas.forEach((schema) => {
      if (schema !== 'public') {
        lines.push(`CREATE SCHEMA IF NOT EXISTS ${quote(schema)};\n`);
      }
    });
  }

  // 2. Drop Foreign Key / Tables if requested
  if (includeDropTable) {
    tables.forEach((table) => {
      const schema = table.schemaName || 'public';
      lines.push(`DROP TABLE IF EXISTS ${quote(schema)}.${quote(table.physicalName)} CASCADE;`);
    });
    if (tables.length > 0) lines.push('');
  }

  // 3. Create Tables
  tables.forEach((table) => {
    const schema = table.schemaName || 'public';
    const tableName = table.physicalName;

    lines.push(`CREATE TABLE ${quote(schema)}.${quote(tableName)} (`);

    const columnDefs: string[] = [];

    const cols = table.columnOrder
      .map((id) => table.columnsById[id])
      .filter((col): col is ColumnModel => col !== undefined);

    cols.forEach((col) => {
      let typeStr = col.type.name.toUpperCase();

      // PostgreSQL type mapping
      if (col.identity) {
        if (typeStr.includes('BIGINT') || typeStr.includes('INT8')) {
          typeStr = 'BIGSERIAL';
        } else {
          typeStr = 'SERIAL';
        }
      } else {
        if (['VARCHAR', 'CHAR', 'VARBINARY'].includes(typeStr)) {
          typeStr += `(${col.type.length || 100})`;
        } else if (['DECIMAL', 'NUMERIC'].includes(typeStr)) {
          const p = col.type.precision || 18;
          const s = col.type.scale || 0;
          typeStr += `(${p}, ${s})`;
        } else if (typeStr === 'DATETIME' || typeStr === 'DATETIME2') {
          typeStr = 'TIMESTAMP';
        }
      }

      let colLine = `    ${quote(col.physicalName)} ${typeStr}`;

      if (!col.identity) {
        if (col.nullable) {
          colLine += ' NULL';
        } else {
          colLine += ' NOT NULL';
        }
      }

      if (col.defaultExpression && !col.identity) {
        colLine += ` DEFAULT ${col.defaultExpression}`;
      }

      columnDefs.push(colLine);
    });

    // Primary Key Constraint
    const pkCols = cols.filter((c) => c.isPk);
    if (pkCols.length > 0) {
      const pkColNames = pkCols.map((c) => quote(c.physicalName)).join(', ');
      columnDefs.push(`    CONSTRAINT ${quote(`PK_${tableName}`)} PRIMARY KEY (${pkColNames})`);
    }

    lines.push(columnDefs.join(',\n'));
    lines.push(');\n');

    // Table & Column Comments
    if (includeComments) {
      if (table.logicalName || table.comment) {
        const commentText = [table.logicalName, table.comment].filter(Boolean).join(' - ');
        lines.push(`COMMENT ON TABLE ${quote(schema)}.${quote(tableName)} IS '${commentText.replace(/'/g, "''")}';`);
      }

      cols.forEach((col) => {
        if (col.logicalName || col.comment) {
          const colCommentText = [col.logicalName, col.comment].filter(Boolean).join(' - ');
          lines.push(
            `COMMENT ON COLUMN ${quote(schema)}.${quote(tableName)}.${quote(col.physicalName)} IS '${colCommentText.replace(/'/g, "''")}';`
          );
        }
      });
      lines.push('');
    }
  });

  // 4. Foreign Keys (ALTER TABLE)
  const sortedRels = Object.values(schemaModel.relationshipsById).sort((a, b) =>
    (a.constraintName || '').localeCompare(b.constraintName || '')
  );

  sortedRels.forEach((rel) => {
    const parent = schemaModel.tablesById[rel.parentTableId];
    const child = schemaModel.tablesById[rel.childTableId];
    if (!parent || !child) return;

    const parentCols = rel.columnMappings
      .map((m) => parent.columnsById[m.parentColumnId]?.physicalName)
      .filter(Boolean)
      .map((name) => quote(name!));

    const childCols = rel.columnMappings
      .map((m) => child.columnsById[m.childColumnId]?.physicalName)
      .filter(Boolean)
      .map((name) => quote(name!));

    if (parentCols.length === 0 || childCols.length === 0) return;

    const constraintName = rel.constraintName || `FK_${child.physicalName}_${parent.physicalName}`;

    lines.push(
      `ALTER TABLE ${quote(child.schemaName || 'public')}.${quote(child.physicalName)}`
    );
    lines.push(
      `    ADD CONSTRAINT ${quote(constraintName)} FOREIGN KEY (${childCols.join(', ')})`
    );
    lines.push(
      `    REFERENCES ${quote(parent.schemaName || 'public')}.${quote(parent.physicalName)} (${parentCols.join(', ')})`
    );

    if (rel.onDelete && rel.onDelete !== 'NO ACTION') {
      lines.push(`    ON DELETE ${rel.onDelete}`);
    }
    if (rel.onUpdate && rel.onUpdate !== 'NO ACTION') {
      lines.push(`    ON UPDATE ${rel.onUpdate}`);
    }

    lines.push(';\n');
  });

  return lines.join('\n');
}
